version: "3"
services:
        login-app:
            container_name: crowdfunder-app
            image: node:latest
            restart: on-failure
            volumes:
                - .:/app
            ports:
                - "3000:3000"
            depends_on:
                - mongo
            command: bash -c "cd /app && npm install && ./wait-for-it/wait-for-it.sh mongo:27017 -- node app.js"
        mongo:
            container_name: mongo
            image: mongo
            volumes:
                - ./data:/data/db
            ports:
                - '27017:27017'

